with staging as (

            select * from {{ source('itrack_fivetran','itrackpopitm') }}

        ),

        final as (

            select
                sha1(array_to_string(array_construct_compact(*),','))       as id,
                acct                                                        as acct,
                calcode                                                     as calcode,
                cirecid                                                     as cirecid,
                contno                                                      as contno,
                costacode                                                   as costacode,
                costlinktype                                                as costlinktype,
                costparitem                                                 as costparitem,
                costrcode                                                   as costrcode,
                delref                                                      as delref,
                depot                                                       as depot,
                discount                                                    as discount,
                duedate                                                     as duedate,
                duetime                                                     as duetime,
                estretd                                                     as estretd,
                estrett                                                     as estrett,
                fixrate                                                     as fixrate,
                fnlcc                                                       as fnlcc,
                fnlcode                                                     as fnlcode,
                fnldept                                                     as fnldept,
                fromtf                                                      as fromtf,
                goods                                                       as goods,
                hiredate                                                    as hiredate,
                hireorsale                                                  as hireorsale,
                hiretime                                                    as hiretime,
                hrrate                                                      as hrrate,
                invdtd                                                      as invdtd,
                invprice                                                    as invprice,
                itemdesc                                                    as itemdesc,
                itemno                                                      as itemno,
                l50dept                                                     as l50dept,
                lastdel                                                     as lastdel,
                lastinv                                                     as lastinv,
                lastinvt                                                    as lastinvt,
                linkedto                                                    as linkedto,
                livepostohqretd                                             as livepostohqretd,
                liveposttype                                                as liveposttype,
                memo                                                        as memo,
                nodays                                                      as nodays,
                noweeks                                                     as noweeks,
                ordno                                                       as ordno,
                paritem                                                     as paritem,
                price                                                       as price,
                projcost                                                    as projcost,
                qtydel                                                      as qtydel,
                qtyinv                                                      as qtyinv,
                qtyord                                                      as qtyord,
                qtyres                                                      as qtyres,
                qtyret                                                      as qtyret,
                ratecode                                                    as ratecode,
                rate_1                                                      as rate_1,
                rate_10                                                     as rate_10,
                rate_2                                                      as rate_2,
                rate_3                                                      as rate_3,
                rate_4                                                      as rate_4,
                rate_5                                                      as rate_5,
                rate_6                                                      as rate_6,
                rate_7                                                      as rate_7,
                rate_8                                                      as rate_8,
                rate_9                                                      as rate_9,
                reason                                                      as reason,
                recid                                                       as recid,
                recorder                                                    as recorder,
                rv                                                          as rv,
                selected                                                    as selected,
                sid                                                         as sid,
                snlcc                                                       as snlcc,
                snlcode                                                     as snlcode,
                snldept                                                     as snldept,
                status                                                      as status,
                strecid                                                     as strecid,
                subtype                                                     as subtype,
                suppno                                                      as suppno,
                type                                                        as type,
                vatcode                                                     as vatcode,
                weight                                                      as weight,
                wrate                                                       as wrate,
                _fivetran_deleted                                           as _fivetran_deleted,
                _fivetran_synced                                            as _fivetran_synced,
      
            from staging

        )

        select * from final