with source as (

            select * from {{ source('itrack_fivetran','itrackinvitems') }}

        ),

        staging as (

            select
                sha1(array_to_string(array_construct_compact(*),','))       as id,
                ADDNHOURS                                                   as addnhours,
                ADMINCOST                                                   as admincost,
                AMENDED                                                     as amended,
                CALNONDAYS                                                  as calnondays,
                CHARGE                                                      as charge,
                CHARGEDISC                                                  as chargedisc,
                CIGROUP                                                     as cigroup,
                CIGROUPNAME                                                 as cigroupname,
                CIPARITEM                                                   as ciparitem,
                CIRECID                                                     as cirecid,
                CONTNO                                                      as contno,
                COST                                                        as cost,
                CREDSUP                                                     as credsup,
                CURRATEID                                                   as currateid,
                DAMFLAG                                                     as damflag,
                DEPOT                                                       as depot,
                DISCFIRST                                                   as discfirst,
                DISCOUNT                                                    as discount,
                DNOTE                                                       as dnote,
                ENDDATE                                                     as enddate,
                ENDTIME                                                     as endtime,
                EXENDDAYS                                                   as exenddays,
                EXHIREDAYS                                                  as exhiredays,
                FARPOSTED                                                   as farposted,
                FARRECID                                                    as farrecid,
                FIXAMT                                                      as fixamt,
                FIXDAYS                                                     as fixdays,
                FIXRATE                                                     as fixrate,
                HDISC                                                       as hdisc,
                HIREDATE                                                    as hiredate,
                HIREDAYS                                                    as hiredays,
                HIRETIME                                                    as hiretime,
                HOMEDEPOT                                                   as homedepot,
                HOURS                                                       as hours,
                INITIAL                                                     as initial,
                INSURANCE                                                   as insurance,
                INVNO                                                       as invno,
                ITEMDESC_1                                                  as itemdesc_1,
                ITEMDESC_2                                                  as itemdesc_2,
                ITEMDESC_3                                                  as itemdesc_3,
                ITEMNO                                                      as itemno,
                L50DEPT                                                     as l50dept,
                LASTINV                                                     as lastinv,
                LINKEDXHIRE                                                 as linkedxhire,
                LOHADDN                                                     as lohaddn,
                LOHDISC                                                     as lohdisc,
                LOSTFLAG                                                    as lostflag,
                MEMO                                                        as memo,
                MEMOVIS                                                     as memovis,
                METEREXTCHARGE                                              as meterextcharge,
                METEREXTHRS                                                 as meterexthrs,
                METEREXTRATE                                                as meterextrate,
                METERSTDCHARGE                                              as meterstdcharge,
                METERSTDHRS                                                 as meterstdhrs,
                METERSTDRATE                                                as meterstdrate,
                NLCC                                                        as nlcc,
                NLCODE                                                      as nlcode,
                NLDEPT                                                      as nldept,
                NODAYS                                                      as nodays,
                NODISC                                                      as nodisc,
                NOWEEKS                                                     as noweeks,
                OHCONT                                                      as ohcont,
                OHNOTE                                                      as ohnote,
                PACKQTY                                                     as packqty,
                PARITEM                                                     as paritem,
                PROJCOST                                                    as projcost,
                QPPDESC                                                     as qppdesc,
                QTY                                                         as qty,
                QTYISS                                                      as qtyiss,
                QTYLRETD                                                    as qtylretd,
                RATECODE                                                    as ratecode,
                READDATE                                                    as readdate,
                READING                                                     as reading,
                RECID                                                       as recid,
                RECORDER                                                    as recorder,
                REFNO                                                       as refno,
                RESOURCE                                                    as resource,
                RETSTOCK                                                    as retstock,
                RSLOT                                                       as rslot,
                RV                                                          as rv,
                SAFEMODE                                                    as safemode,
                SAFETYPE                                                    as safetype,
                SID                                                         as sid,
                SUBTYPE                                                     as subtype,
                SUSP                                                        as susp,
                TOFOLLOW                                                    as tofollow,
                TSREC                                                       as tsrec,
                TYPE                                                        as type,
                UEENDDATE                                                   as ueenddate,
                UEHIREDATE                                                  as uehiredate,
                VATCODE                                                     as vatcode,
                WRATE                                                       as wrate,
                _FIVETRAN_DELETED                                           as _fivetran_deleted,
                _FIVETRAN_SYNCED                                            as _fivetran_synced,
      
            from source

        )

        select * from staging