with source as (

            select * from {{ source('itrack_fivetran','itrackinvhdr') }}

        ),

        staging as (

            select
                sha1(array_to_string(array_construct_compact(*),','))       as id,
                ACCT                                                        as acct,
                ACCTNAME                                                    as acctname,
                ADDR_1                                                      as addr_1,
                ADDR_2                                                      as addr_2,
                ADDR_3                                                      as addr_3,
                ADDR_4                                                      as addr_4,
                AFTDISC                                                     as aftdisc,
                AFTSETT                                                     as aftsett,
                ALLOCFLAG                                                   as allocflag,
                AMTPAID                                                     as amtpaid,
                BATCHNO                                                     as batchno,
                CASHALLOC                                                   as cashalloc,
                CASHPOSTED                                                  as cashposted,
                CASHREC                                                     as cashrec,
                COLLCHG                                                     as collchg,
                CONTNO                                                      as contno,
                CREDSUPAMT                                                  as credsupamt,
                CREDSUPCDE                                                  as credsupcde,
                CURRENCY                                                    as currency,
                DATE                                                        as date,
                DELADDR_1                                                   as deladdr_1,
                DELADDR_2                                                   as deladdr_2,
                DELADDR_3                                                   as deladdr_3,
                DELADDR_4                                                   as deladdr_4,
                DELCHG                                                      as delchg,
                DELCODE                                                     as delcode,
                DELEMAIL                                                    as delemail,
                DELNAME                                                     as delname,
                DELNOTE                                                     as delnote,
                DELPCODE                                                    as delpcode,
                DEPOSIT                                                     as deposit,
                DISCOUNT                                                    as discount,
                EGOODS                                                      as egoods,
                EMAILOUTSTANDING                                            as emailoutstanding,
                EMAILRESENT                                                 as emailresent,
                EMAILRESENTTIME                                             as emailresenttime,
                EMAILSENT                                                   as emailsent,
                EMAILSENTTIME                                               as emailsenttime,
                ENDDATE                                                     as enddate,
                ENDTIME                                                     as endtime,
                EOD                                                         as eod,
                EURO                                                        as euro,
                EVAT                                                        as evat,
                EXRATE                                                      as exrate,
                FCAFTDISC                                                   as fcaftdisc,
                FCGOODS                                                     as fcgoods,
                FCPRICES                                                    as fcprices,
                FCVAT                                                       as fcvat,
                GOODS                                                       as goods,
                HIREDATE                                                    as hiredate,
                HIREDEPOT                                                   as hiredepot,
                HIRETIME                                                    as hiretime,
                INS                                                         as ins,
                INSTAXCODE                                                  as instaxcode,
                INSTAXINC                                                   as instaxinc,
                INSTAXRATE                                                  as instaxrate,
                INSTOT                                                      as instot,
                INVNO                                                       as invno,
                INVTYPE                                                     as invtype,
                MANUAL                                                      as manual,
                OHTYPE                                                      as ohtype,
                ORDEREDBY                                                   as orderedby,
                PAYMETH                                                     as paymeth,
                PICKLIST                                                    as picklist,
                POSTCODE                                                    as postcode,
                POSTED                                                      as posted,
                POSTEDEDI                                                   as postededi,
                POSTEDJC                                                    as postedjc,
                POSTJC                                                      as postjc,
                POSTSL                                                      as postsl,
                PROFORMA                                                    as proforma,
                REASONCODE                                                  as reasoncode,
                REASONTEXT                                                  as reasontext,
                RECID                                                       as recid,
                RECORDER                                                    as recorder,
                REVERSECHARGE                                               as reversecharge,
                RV                                                          as rv,
                S50TRAN                                                     as s50tran,
                SELLHIRE                                                    as sellhire,
                SETTDAYS                                                    as settdays,
                SETTDISC                                                    as settdisc,
                SID                                                         as sid,
                SOURCE                                                      as source,
                SPCODE                                                      as spcode,
                STATUS                                                      as status,
                TAXAREACODE                                                 as taxareacode,
                TELNO                                                       as telno,
                TERMS                                                       as terms,
                THEIRREF                                                    as theirref,
                UPDATEITEM                                                  as updateitem,
                VAT                                                         as vat,
                YOURREF                                                     as yourref,
                _FIVETRAN_DELETED                                           as _fivetran_deleted,
                _FIVETRAN_SYNCED                                            as _fivetran_synced,
      
            from source

        )

        select * from staging